#!/usr/bin/env python3
from pathlib import Path
import argparse, re, sys

REQUIRED = {24,32,48,64,96,256}
ALLOWED={"resize_algorithm","hotspot_x","hotspot_y","define_override","define_size"}

ap=argparse.ArgumentParser()
ap.add_argument("theme", type=Path)
args=ap.parse_args()

root=args.theme
manifest=root/"manifest.hl"
if not manifest.exists():
    raise SystemExit("missing manifest.hl")

m=re.search(r"(?m)^\s*cursors_directory\s*=\s*([^#\n]+)",manifest.read_text())
if not m:
    raise SystemExit("missing cursors_directory")

cdir=root/m.group(1).strip()
if not cdir.is_dir():
    raise SystemExit(f"missing {cdir}")

ok=True
checked_brushbuddy=0

for shape in sorted(p for p in cdir.iterdir() if p.is_dir()):
    meta=shape/"meta.hl"
    if not meta.exists():
        print("missing meta:",shape)
        ok=False
        continue

    txt=meta.read_text()
    sizes=[]
    brushbuddy=False

    for n,line in enumerate(txt.splitlines(),1):
        s=line.split("#",1)[0].strip()
        if not s:
            continue
        if "=" not in s:
            print(f"{meta}:{n}: malformed: {line}")
            ok=False
            continue

        key=s.split("=",1)[0].strip()
        if key not in ALLOWED:
            print(f"{meta}:{n}: unexpected key {key!r}")
            ok=False

        if key == "define_size":
            parts=[p.strip() for p in s.split("=",1)[1].split(",")]
            if len(parts) not in (2,3):
                print(f"{meta}:{n}: bad define_size: {line}")
                ok=False
                continue

            try:
                size=int(parts[0])
                sizes.append(size)
            except ValueError:
                print(f"{meta}:{n}: invalid size: {parts[0]}")
                ok=False
                continue

            filename=parts[1]
            if re.fullmatch(r"frame_(24|32|48|64|96|256)_\d{3}\.png", filename):
                brushbuddy=True

            img=shape/filename
            if not img.exists():
                print(f"{meta}:{n}: missing image {filename}")
                ok=False

            if len(parts)==3:
                try:
                    timeout=int(parts[2])
                    if timeout <= 0:
                        print(f"{meta}:{n}: non-positive animation timeout")
                        ok=False
                except ValueError:
                    print(f"{meta}:{n}: invalid timeout {parts[2]}")
                    ok=False

    # IMPORTANT: enforce the six-size ladder only on shapes generated by this kit.
    if brushbuddy:
        checked_brushbuddy += 1
        missing=REQUIRED-set(sizes)
        if missing:
            print(f"{meta}: missing Brushbuddy size(s): {sorted(missing)}")
            ok=False

print(f"Brushbuddy shapes checked: {checked_brushbuddy}")
print("OK" if ok else "FAILED")
sys.exit(0 if ok else 1)
